// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhoAmI.Infrastructure.Data.Persistence.Context;

#nullable disable

namespace WhoAmI.Infrastructure.Migrations
{
    [DbContext(typeof(WhoAmIDbContext))]
    partial class WhoAmIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("WhoAmI.Domain.Profiles.Profile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("GitHub")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("github_url");

                    b.Property<string>("LinkedIn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("linkedin_url");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Profiles_Email");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("UX_Profiles_Guid");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("WhoAmI.Domain.Profiles.Profile", b =>
                {
                    b.OwnsOne("WhoAmI.Domain.Profiles.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<string>("ProfileId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");

                            b1.OwnsOne("WhoAmI.Domain.Profiles.ValueObjects.FirstName", "FirstName", b2 =>
                                {
                                    b2.Property<string>("FullNameProfileId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("first_name");

                                    b2.HasKey("FullNameProfileId");

                                    b2.ToTable("Profiles");

                                    b2.WithOwner()
                                        .HasForeignKey("FullNameProfileId");
                                });

                            b1.OwnsOne("WhoAmI.Domain.Profiles.ValueObjects.LastName", "LastName", b2 =>
                                {
                                    b2.Property<string>("FullNameProfileId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("last_name");

                                    b2.HasKey("FullNameProfileId");

                                    b2.ToTable("Profiles");

                                    b2.WithOwner()
                                        .HasForeignKey("FullNameProfileId");
                                });

                            b1.Navigation("FirstName")
                                .IsRequired();

                            b1.Navigation("LastName")
                                .IsRequired();
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
